In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/IMDB Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.shape

(50000, 2)

In [7]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [10]:
df.drop_duplicates(inplace=True)
df.shape

(49582, 2)

### Text - Preprocessing

In [11]:
# Converting in lowercase
df["review"] = df["review"].str.lower()

In [12]:
# Removing the urls
import re

def remove_urls(text):
    return re.sub(r"http\S+", "", text)

df["review"] = df["review"].apply(remove_urls)

In [13]:
# Removing Punctuations

def remove_punctuations(text):
    return re.sub(r"[^\w\s]", "", text)

df["review"] = df["review"].apply(remove_punctuations)

In [14]:
# Removing HTML Tags

def remove_html(text):
    return re.sub(r"<.*?>", "", text)

df["review"] = df["review"].apply(remove_html)

In [16]:
# Removing the stopwords

import nltk

# nltk.download("punkt")
# nltk.download("punkt_tab")
# nltk.download("stopwords")

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [21]:
stop_words = set(stopwords.words("english"))

negation_words = {
    "not", "no", "nor", "never",
    "neither", "n't"
}

stop_words -= negation_words

In [24]:
def remove_stopwords(text):
    tokens = word_tokenize(text)

    filtered_tokens = []

    for word in tokens:
        if word not in stop_words:
            filtered_tokens.append(word)

    return " ".join(filtered_tokens)
    
df["review"] = df["review"].apply(remove_stopwords)

In [25]:
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production br br filming tech...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive